paths:
  /api/products_mongo:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: Products were served correctly
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Internal server error getting products
    post:
      summary: Create a product
      tags:
        - Products
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"

  /api/products_mongo/{uid}:
    get:
      summary: Get a product by ID
      tags:
        - Products
      parameters:
        - name: uid
          in: path
          required: true
          description: Product ID required
          schema:
            type: string
      responses:
        "200":
          description: Product was served correctly
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Internal server error getting product
    put:
      summary: Update a product by ID
      tags:
        - Products
      parameters:
        - name: uid
          in: path
          required: true
          description: Product ID required
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          description: Autogenerated mongo id
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product details
        stock:
          type: number
          description: Product stock
        thumbnail:
          type: string
          description: Product picture
        price:
          type: number
          description: Product price
      example:
        id: "3rewfq325t254tefwr253twe"
        title: Rose
        description: Rose flowers vary in size and shape. They burst with colors ranging from pastel pink, peach, and cream, to vibrant yellow, orange, and red
        stock: 24
        thumbnail: https://picsum.photos/200/300
        price: 10

  requestBodies:
    updateProducts:
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: Product title
              description:
                type: string
                description: Product details
              stock:
                type: number
                description: Product stock
              thumbnail:
                type: string
                description: Product picture
              price:
                type: number
                description: Product price
          example:
            title: Rose
            description: Rose flowers vary in size and shape. They burst with colors ranging from pastel pink, peach, and cream, to vibrant yellow, orange, and red
            stock: 24
            thumbnail: https://picsum.photos/200/300
            price: 10
