apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubeusers39770
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: kubeusers39770
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeusers39770
  template:
    metadata:
      labels:
        app: kubeusers39770
  spec:
    containers:
      - name: kubecontainer
        image: andy/usercreator:1.0.0
        ports:
          - containerPort: 8080
        env:
          - name: MONGO_URL
            value: mongodb+srv://Andresito:OTQjdcLN2um338qI@coderhouse.m53mktc.mongodb.net/commerce
        imagePullPolicy: Always