config:
  plugins:
    metrics-by-endpoint: {}
  target: "http://localhost:8080"
  phases:
    - duration: 20
      arrivalRate: 10
scenarios:
  - name: "Sessions Flow (Register + Login)"
    flow:
    - log: "Creating test user"
    - get:
      url: /api/auth/testUser
      capture:
      - json: "$.first_name"
        as: 'first_name'
      - json: "$.last_name"
        as: 'lastName'
      - json: "$.email"
        as: 'email'
      - json: "$.password"
        as: 'password'
    - log: 'User Registered'
    - post:
        url: /api/sessions/Register
        json:
          first_name: "{{first_name}}"
          last_name: "{{last_name}}"
          email: "{{email}}"
          password: "{{password}}"
    - think: 2
    - log: 'User logged'
    - post:
        url: '/api/session/login'
        json:
          email: "{{email}}"
          password: "{{password}}"